version: '3'
services:
  test-media-downloader-service:
    build: .
    image: media-downloader
    volumes: 
      - ./projects:/code
      - ./download:/download
    working_dir: /root/sources/test/python
    command: python test.py

